### ISSUE TITLE
Matriz de riesgo

### ISSUE THREAD

**Issue by jhuante** [NetVaIT/SOFOM#1]
Generar un nuevo modulo que permita un cuestionario configurable y que afecte en base a una ponderacion el campod Personas.IdRiesgoTipo.

[Matriz de riesgo mañarina V1.xlsx](https://github.com/NetVaIT/SOFOM/files/2228511/Matriz.de.riesgo.manarina.V1.xlsx)

**Comment by aalarcon2015** [comment]
Carlos me indicó por  teléfono que la evaluación de las listas de personas expuestas se realizaba previa a la aplicación  del cuestionario de la matriz de riesgos, pero ahora envía una modificación a la matriz de donde hay que aclarar si se tiene que hacer algo mas en el cuestionario.
Indica lo siguiente:
"Si sale en algún país no cooperante o   paraiso fiscal en automatico es Alto riesgo
Si es PPE extranjera en automatico es   alto riesgo. " 
Esto no se si es nuevo o es de la información que ya se tiene en el sistema.
[Matriz de riesgo mañarina V2.xlsx](https://github.com/NetVaIT/SOFOM/files/2229811/Matriz.de.riesgo.manarina.V2.xlsx)

**Comment by aalarcon2015** [comment]
Por otro lado indica que hay ciertas preguntas que para ciertos tipos de personas no se debe contar. Verificar si solo se separan entre personas físicas y morales o si  hace diferenciación entre los 5 tipos de personas que maneja en las respuestas del cuestionario.
Diseño versión 1:
Esta versión, está diseñada según el esquema en que  cada cuestionario tiene n preguntas y cada  pregunta pueden tener m respuestas e incluir una respuesta de “Otro” que requiera especificar un dato adicional, el cual puede ser colocado de forma manual o a través de algún catálogo de la información existente en sistema(la cual debería tener un campo descripción y de preferencia un campo de UsoComun y en la respuesta del cliente se guardaría el texto) 
[diseñoRiesgo.xlsx](https://github.com/NetVaIT/SOFOM/files/2229879/disenoRiesgo.xlsx)

**Comment by aalarcon2015** [comment]
Se pidió la generación de la versión definitiva de la matriz de riesgos y se recibió el documento  por parte de Carlos con las aclaraciones.  Se procede a evaluar los ajustes requeridos en el diseño para dar soporte a esa matriz.
[Matriz de riesgo mañarina V2DEfinitiva.xlsx](https://github.com/NetVaIT/SOFOM/files/2232815/Matriz.de.riesgo.manarina.V2DEfinitiva.xlsx)

**Comment by aalarcon2015** [comment]
Estructura ajustada con datos vistos en la reunión.
[diseñoRiesgoV2.xlsx](https://github.com/NetVaIT/SOFOM/files/2237045/disenoRiesgoV2.xlsx)

**Comment by aalarcon2015** [comment]
Se generó el Script de los cambio para la implementación de la matriz de Riesgo.
[ScripAjusteMR.txt](https://github.com/NetVaIT/SOFOM/files/2241857/ScripAjusteMR.txt)

**Comment by aalarcon2015** [comment]
Captura de configuración del cuestionario de la matriz de riesgo en proceso. Pendiente de pruebas . No se ha actualizado aun el control de versiones con los últimos cambios.

**Comment by aalarcon2015** [comment]
Se actualizó el control de versiones con la configuración completa del cuestionario.

**Comment by aalarcon2015** [comment]
SE termino el proceso , queda en estado de revisión.

**Comment by aalarcon2015** [comment]
Ultima versión  del Script
[ScripAjusteMR.txt](https://github.com/NetVaIT/SOFOM/files/2295006/ScripAjusteMR.txt)

**Comment by jhuante** [comment]
Fallo parte del script:
Mens. 102, Nivel 15, Estado 1, Línea 124
Incorrect syntax near '_MRPreguntasOpciones'
--Relaciones MRTablasAsociadasCampos 
ALTER TABLE MRTablasAsociadasCampos WITH CHECK ADD  CONSTRAINT FK_MRTablasAsociadasCampos _MRPreguntasOpciones FOREIGN KEY(IdMRPreguntaOpcion)
REFERENCES MRPreguntasOpciones(IdMRPreguntaOpcion)
GO

Mens. 544, Nivel 16, Estado 1, Línea 3
Cannot insert explicit value for identity column in table 'MRCuestionariosEstatus' when IDENTITY_INSERT is set to OFF.
Mens. 544, Nivel 16, Estado 1, Línea 5
Cannot insert explicit value for identity column in table 'MRCuestionariosEstatus' when IDENTITY_INSERT is set to OFF.
Mens. 544, Nivel 16, Estado 1, Línea 7
Cannot insert explicit value for identity column in table 'MRCuestionariosEstatus' when IDENTITY_INSERT is set to OFF.
INSERT INTO MRCuestionariosEstatus  (IDMRCuestionarioEstatus,Identificador,Descripcion) VALUES  (0,'C','Creación'); 
INSERT INTO MRCuestionariosEstatus  (IDMRCuestionarioEstatus,Identificador,Descripcion) VALUES  (1,'A','Activo');
INSERT INTO MRCuestionariosEstatus  (IDMRCuestionarioEstatus,Identificador,Descripcion) VALUES  (2,'I','Inactivo');

**Comment by aalarcon2015** [comment]
Versión Corregida Script
[ScripAjusteMR_Corregido.txt](https://github.com/NetVaIT/SOFOM/files/2297665/ScripAjusteMR_Corregido.txt)

**Comment by aalarcon2015** [comment]
Ya se realizaron las correcciones del script en la base de datos de Producción.

**Comment by jhuante** [comment]
Se reviso modulo de Evaluación de riesgo y Matriz de riesgo:
1. Cambiar las etiquetas tanto en la rejilla como en la edición para que solo la primera palabra se coloque la primera letra en mayúscula
2. Ajustar los diálogos de edición 
![image](https://user-images.githubusercontent.com/4365813/44272547-c85d6b80-a202-11e8-9eac-d4366c4c42b6.png)
![image](https://user-images.githubusercontent.com/4365813/44272586-e88d2a80-a202-11e8-971d-e1a1d0a842dc.png)
3. La pantalla donde realiza la evaluación ponerla en dialogo ya que permite maximizarla y minimizarla.
4. Inhabilitar en el cliente el campo Riesgo.

**Comment by jhuante** [comment]
Se detecto un AV al momento de aplicar el cuestionario, al parecer es por que no se selecciono una versión del cuestionario.
![image](https://user-images.githubusercontent.com/4365813/44272932-bdefa180-a203-11e8-9add-f8e8d6db529c.png)

**Comment by aalarcon2015** [comment]
Oscar sugiere poner estatus al cuestionario aplicado al cliente para que sólo se muestre el vigente, de tal forma que sólo muestre el ultimo aplicado por cliente..(Pendiente)

**Comment by jhuante** [comment]
Revizado
