### ISSUE TITLE
Que los pagos se puedan aplicar a diferentes contratos de un mismo cliente

### ISSUE THREAD

**Issue by jhuante** [NetVaIT/SOFOM#11]

**Comment by aalarcon2015** [comment]
Se generara una estructura de Pagos Reales , que se ubicará en un nivel superior a los pagos existentes, de tal forma que los pagos existentes queden relacionados como hijos de esos pagos reales.
Script de actualización de la BD, 
[scrptAjustePagosReales.txt](https://github.com/NetVaIT/SOFOM/files/2315653/scrptAjustePagosReales.txt)

**Comment by aalarcon2015** [comment]
Listo para revisar y liberar , colocado en Control de Versiones.  Se ajustó filtro en aplicaciones para que aparezcan las cuentas por cobrar correspondientes al anexo del Pago o en su caso sin anexo .

**Comment by jhuante** [comment]
Fue validado y revisado con usuario final

**Comment by jhuante** [comment]
Verificar el calculo del saldo de los pagos, debido al crear nuevo pago y al aplicarlo no esta calculado correctamente.
![image](https://user-images.githubusercontent.com/4365813/46967705-eca8bd80-d076-11e8-986e-1c056847e730.png)
