### ISSUE TITLE
Rediseño de reestructura

### ISSUE THREAD

**Issue by jhuante** [NetVaIT/SOFOM#23]

**Comment by jhuante** [comment]
Angela en base a lo que platicamos favor de tomar la parte de aplicaciones. Se deberá de ajustar el esquema para que tome en cuenta la aplicación de pagos para las CXC - facturas anteriores en una reestructura.

**Comment by aalarcon2015** [comment]
Proceso de aplicación para reestructura terminado ,pendiente de terminar pruebas de CFDIs de Pagos por falta de timbrado de facturas generadas por la reestructura.

**Comment by jhuante** [comment]
La modificacion para las CXC terminado.

**Comment by jhuante** [comment]
Se agrega script de ajustes para la BD.

[ScriptV2_AjustePagosReestructura.txt](https://github.com/NetVaIT/SOFOM/files/2681244/ScriptV2_AjustePagosReestructura.txt)
