### ISSUE TITLE
Modificar interfaz de cobranza-Seguimiento CRM

### ISSUE THREAD

**Issue by jhuante** [NetVaIT/SOFOM#28]

**Comment by aalarcon2015** [comment]
Se solicitó a Carlos la indicación de los cambios que solicitaban desde el 5 de Diciembre. Me dijo que lo estaba revisando.. Se analizará de forma paralela para sugerir algún cambio, por si no se obtiene respuesta de su parte..

**Comment by aalarcon2015** [comment]
Se separaron los dos esquemas de seguimiento. Por cliente o por programación de próximos contactos. 
Se agregó filtro por la calificación de los clientes.

Proceso terminado para revisión.
