### ISSUE TITLE
Envío de factura por medio del sistema

### ISSUE THREAD

**Issue by jhuante** [NetVaIT/SOFOM#29]

**Comment by aalarcon2015** [comment]
Se agregaron  campos a la tabla de configuraciones para poder guardar la información del correo de salida.
ALTER TABLE dbo.Configuraciones ADD
	CECorreoSalida varchar(150) NULL,
	CEHostSalida varchar(50) NULL,
	CEPuetoSalida varchar(20) NULL,
	CEUsuarioSalida varchar(100) NULL,
	CEPasswordSalida varchar(20) NULL,
	CETipoSeguridadSal varchar(20) NULL,
	CETipoAutenticaSal varchar(20) NULL
GO
Se modificó interfaz de captura para modulo de configuración para poder capturar estos datos y se coloco mecanismo de prueba de envío.

**Comment by aalarcon2015** [comment]
Se coloco el envío de los correos desde la consulta de los CFDIs. Con los parámetros preestablecidos se muestra la ventana de correo y ahí se pueden modificar los correos destinatarios, el asunto y el contenido del Correo. En pruebas el sistema siempre envía el correo a: aban@floresgaribay.com,mx, para evitar que les llegue basura a los clientes.

Se hizo un pequeño ajuste en la Cancelación y en Consulta de los estatus de los CFDis para que  envíe de forma correcta los datos de Total y pueda encontrar los CFDIs en SAT. Se cambio el llamado de la Consulta de los estatus  para corregir el problema de disponibilidad del SAT.
Se actualizó en control de versiones
