### ISSUE TITLE
Revisión proceso de cancelación de pagos para liberar aplicación

### ISSUE THREAD

**Issue by aalarcon2015** [NetVaIT/SOFOM#31]
La cancelación del timbre de pago, mantiene la relación con la tabla de Pago aplicación por lo tanto la aplicación no puede ser eliminada. El procedimiento se realiza de forma parcial  y deja la aplicación disponible , por lo que al intentar borrarla nuevamente, el saldo del pago se incremente indefinidamente.

**Comment by jhuante** [comment]
Se realiza el ajuste del procedimiento 
[p_CanCFDI.txt](https://github.com/NetVaIT/SOFOM/files/2751422/p_CanCFDI.txt)
