### ISSUE TITLE
Revisión de proceso de aplicación de Abonos a Capital  

### ISSUE THREAD

**Issue by aalarcon2015** [NetVaIT/SOFOM#32]
Hay que verificar el proceso para cuando no aparece el saldo insoluto (verificar si esto se puede controlar o al menos avisar la razón por la que no se puede aplicar) y verificar porque una aplicación a capital  hace un doble descuento del Saldo. Verificar datos enviados.

**Comment by aalarcon2015** [comment]
Se ajustó proceso para aplicación de abonos a capital en caso que existan CXC pendientes y no facturadas, para que el usuario se entere el porqué no se puede seguir.. Se envían mensajes indicando la situación y el usuario debe tomar la decisión de que hacer.

**Comment by jhuante** [comment]
Adicionamente se encontró al momento de generar el ajuste a las mensualidades del contrato pareciera que se duplica el importe.

**Comment by jhuante** [comment]
Se realizo el ajuste en PagosDM se cambio la accion actCrearCXCAbonoCapital por  actAbonarCapital.
