### ISSUE TITLE
Manejo de usuarios a través de perfiles.

### ISSUE THREAD

**Issue by aalarcon2015** [NetVaIT/SOFOM#33]
Implementar esquema de seguridad a través de perfiles de usuario

**Comment by aalarcon2015** [comment]
Ajustes a la base de datos
CREATE TABLE UsuariosPerfiles(
	IdUsuarioPerfil int IDENTITY(1,1) NOT NULL  Primary key,
	Descripcion varchar(25) NULL,
	PermisoMenu varchar(300) NULL,
	PermisoOpcion varchar(500) NULL,
	PermisosFuncion varchar(300) NULL)



ALTER TABLE dbo.Usuarios ADD
       IdUsuarioPerfil int NULL,
	Permisos varchar(255) NULL
GO

ALTER TABLE dbo.Usuarios ADD CONSTRAINT
	FK_Usuarios_UsuariosPerfiles FOREIGN KEY
	(
	IdUsuarioPerfil
	) REFERENCES dbo.UsuariosPerfiles
	(
	IdUsuarioPerfil
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO

**Comment by aalarcon2015** [comment]
Ajuste terminado en etapa de pruebas. Par usar en producción se deben crear los perfiles y asociarlos a los usuarios. Inicialmente se generará Script con perfil administrador y se asocia a todos los usuarios vigentes ese perfil. Script pendiente de generar y probar..

**Comment by aalarcon2015** [comment]
Actualización de datos en BD

INSERT INTO UsuariosPerfiles (Descripcion
           ,PermisoMenu
           ,PermisoOpcion
           ,PermisosFuncion)
     VALUES
           ('Administrador'
           ,'1|2|3|'
           ,'1|2|3|6|5|100|29|61|8|10|4|5|11|13|22|23|28|21|20|65|31|62|36|30|33|32|38|63|34|40|35|37|39|55|52|56|57|50|54|51|53|60|64|58|'
           ,NULL)


Update Usuarios set idUsuarioPerfil=1 where idusuarioEstatus=1 -- solo los activos

**Comment by aalarcon2015** [comment]
Ya quedó actualizada la verion en el control de versiones . La base de datos de Mañarina ya tiene los datos

**Comment by jhuante** [comment]
Al realizar un a prueba desconectando el usuario quedan algunos accesos habilitados, favor de revisar.
![image](https://user-images.githubusercontent.com/4365813/51625780-aa0f4080-1f03-11e9-87bf-cf20fd2093a2.png)

**Comment by aalarcon2015** [comment]
corregido
