### ISSUE TITLE
En las aplicaciones de pago estan apareciendo CXC canceladas.

### ISSUE THREAD

**Issue by jhuante** [NetVaIT/SOFOM#39]
En las aplicaciones de pago están apareciendo CXC canceladas, este contrato tiene una reestructura y aparecen las CXC 

![image](https://user-images.githubusercontent.com/4365813/52067510-5a062e80-2540-11e9-8117-483ed7b32542.png)

**Comment by aalarcon2015** [comment]
Se ajustaron PagosDM y AplicacionesPagos. También se ajustaron consultas para seguimiento
